### PR TITLE
feat: add signet and testnet4 addresses

### PR DESCRIPTION
**Pull request by gartnera**
The generator wasn't working so I added these by hand. The generator code also needs to be updated to correctly handle these new networks.

Related to https://github.com/zeta-chain/node/issues/2242

## Summary by CodeRabbit

- **New Features**
	- Added support for two new omnichain entries: `btc_signet` and `btc_testnet4`.

- **Improvements**
	- Enhanced data handling for address management to prevent duplicate entries in the address list.

- **Type Updates**
	- Updated chain name definitions to include new values and remove obsolete ones.

- **Workflows**
	- Removed obsolete GitHub Actions workflows for generated files and testing.

### CODE REVIEW

**Comment by fadeev** [comment]
@gartnera ZRC-20 addresses are fetched automatically from https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/fungible/foreign_coins.

Can you, please, move:

```json
  {
    "address": "tb1qy9pqmk2pd9sv63g27jt8r657wy0d9ueeh0nqur",
    "category": "omnichain",
    "chain_id": 18333,
    "chain_name": "btc_signet",
    "type": "tss"
  },
  {
    "address": "tb1qy9pqmk2pd9sv63g27jt8r657wy0d9ueeh0nqur",
    "category": "omnichain",
    "chain_id": 18334,
    "chain_name": "btc_testnet4",
    "type": "tss"
  },
```

To [`addresses.testnet.json`](https://github.com/zeta-chain/protocol-contracts/blob/5368eb80e842a0f42eb52e6f94b6b0119671c4a7/v2/tasks/addresses.testnet.json) so they're not overwritten when the script runs again.

**Review by andresaiello — APPROVED** [review]

**Comment by gartnera** [comment]
> @gartnera ZRC-20 addresses are fetched automatically from https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/fungible/foreign_coins.

So I/we can remove all the zrc20 entries?

> Can you, please, move:
> 
> ```json
>   {
>     "address": "tb1qy9pqmk2pd9sv63g27jt8r657wy0d9ueeh0nqur",
>     "category": "omnichain",
>     "chain_id": 18333,
>     "chain_name": "btc_signet",
>     "type": "tss"
>   },
>   {
>     "address": "tb1qy9pqmk2pd9sv63g27jt8r657wy0d9ueeh0nqur",
>     "category": "omnichain",
>     "chain_id": 18334,
>     "chain_name": "btc_testnet4",
>     "type": "tss"
>   },
> ```
> 
> To [`addresses.testnet.json`](https://github.com/zeta-chain/protocol-contracts/blob/5368eb80e842a0f42eb52e6f94b6b0119671c4a7/v2/tasks/addresses.testnet.json) so they're not overwritten when the script runs again.

I already have entries in the addresses.testnet.json file?

**Comment by fadeev** [comment]
@gartnera not exactly.

This script: https://github.com/zeta-chain/protocol-contracts/blob/main/v2/tasks/addresses.ts

And this file (containing addresses we can't fetch automatically): https://github.com/zeta-chain/protocol-contracts/blob/main/v2/tasks/addresses.testnet.json (note it's in the tasks dir) ❗️ I propose we add Bitcoin TSS addresses to this file and not the auto-generated file.

Results in this auto-generated file: https://github.com/zeta-chain/protocol-contracts/blob/main/v2/data/addresses.testnet.json (note it's in the data dir)

**Comment by fadeev** [comment]
I know this system is crap (auto-generation breaking), but the one we had before (manually maintained file, wrong addreses everywhere) was even worse.

Let's do it right this time! 😃

https://www.notion.so/zetachain/Contract-Address-Registry-1517b3fb9049800e9eb4e292ca9867f0?pvs=4

**Comment by gartnera** [comment]
Ok @fadeev I think I know what you're saying. I've updated the PR.

If this still isn't correct maybe you could fix it up?

**Comment by fadeev** [comment]
Removed testnet 4 and signet addresses from the manual JSON file, because they're fetched automatically. Updated the script to take chain names from `name` rather than `chain_name` from https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/observer/supportedChains For some reason `chain_name` is `"ampty"` for BTC testnets.

**Comment by fadeev** [comment]
CI is failing because RPC endpoints are blocking requests.

**Review by lumtis — APPROVED** [review]

**Comment by lumtis** [comment]
> CI is failing because RPC endpoints are blocking requests.

This is for v1 it doesn't matter anymore isn't it?

**Comment by fadeev** [comment]
> > CI is failing because RPC endpoints are blocking requests.
> 
> This is for v1 it doesn't matter anymore isn't it? @fadeev

🤦‍♂️ I didn't notice it's only failing for v1. Yes, we can merge, and then disable generated CI for v1.

**Comment by fadeev** [comment]
In fact, shall I disable both generated and test for v1, so we have clean CI before merging?

**Comment by lumtis** [comment]
> In fact, shall I disable both generated and test for v1, so we have clean CI before merging?

Yes

**Pull request merged**
