### PR TITLE
Fix solidy from 0.8.7 to ^0.8.0 and fix build command failed issue

### PR DESCRIPTION
**Pull request by lispking**
## Summary by CodeRabbit

- **New Features**
	- Updated Solidity version constraints across multiple contracts to allow compatibility with any version from 0.8.0 up to, but not including, 0.9.0, enhancing flexibility and future-proofing.

- **Bug Fixes**
	- Adjusted documentation to reflect the newer compiler version (0.8.18) in both the configuration and testing instructions, ensuring users are directed to use the latest tools.

- **Chores**
	- Upgraded the Uniswap library dependency version in the project configuration.

### CODE REVIEW

**Review by lumtis — COMMENTED** [review]
I may think it is in general a better practice to specify a fixed version for Solidity if these are production contracts

**Comment by lispking** [comment]
The specific version should be resolved by the compiler, not hardcoded into the code like this. @lumtis

**Comment by lispking** [comment]
These are all industry best practices.

For example, with a library like IERC20, a similar approach is taken by specifying a minimum version requirement: 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/IERC20.sol

**Comment by fadeev** [comment]
@lispking thanks for taking the time to look into versions of the protocol contracts! It's up to the protocol team to decide how to move forward, but if you want to contribute to ZetaChain on a more regular basis, consider the tech ambassador program: https://zetachain.deform.cc/TechAmbassadors 🙌

**Comment by lumtis** [comment]
Hi @lispking , we are currently in the process of refactoring the environment to have v1 and v2 contracts separated and use latest Solidity version for v2 contracts.

v1 contracts are no longer in active development.

Did you want this change for some specific contracts in the codebase?

**Comment by lispking** [comment]
> Hi @lispking , we are currently in the process of refactoring the environment to have v1 and v2 contracts separated and use latest Solidity version for v2 contracts.
> 
> v1 contracts are no longer in active development.
> 
> Did you want this change for some specific contracts in the codebase?

@lumtis Sure, no problem. Which is the codebase contract address? If needed, I can help with modifications and testing.

If there are no issues with this, it can be merged first. thx.

**Comment by lumtis** [comment]
> > Hi @lispking , we are currently in the process of refactoring the environment to have v1 and v2 contracts separated and use latest Solidity version for v2 contracts.
> > v1 contracts are no longer in active development.
> > Did you want this change for some specific contracts in the codebase?
> 
> @lumtis Sure, no problem. Which is the codebase contract address? If needed, I can help with modifications and testing.
> 
> If there are no issues with this, it can be merged first. thx.

This is the PR for separating the two codebases: https://github.com/zeta-chain/protocol-contracts/pull/268

To reduce the overhead on conflicts, we will prioritize merging it. We can check if there is still an issue afterward.

**Comment by andresaiello** [comment]
> I may think it is in general a better practice to specify a fixed version for Solidity if these are production contracts

in general every audit (I had several) recommend to use a fixed version. The main reason is to guarantee if someone else (or you on test enviroments) wants to replicate can be sure to have the same results. I have opposite feelings about this but according to audits always is fixed.

**Comment by lumtis** [comment]
Closing as version as been updated for contracts V2

**Pull request closed without merging**
