### PR TITLE
feat: add tBTC ZRC-20 address to addresses.json

### PR DESCRIPTION
**Pull request by fadeev**

### CODE REVIEW

**Review by btroo — APPROVED** [review]

**Comment by fadeev** [comment]
@andresaiello please, review.

**Review by andresaiello — APPROVED** [review]

**Comment by fadeev** [comment]
@lucas-janon we need a second approving review to merge.

**Review by lucas-janon — APPROVED** [review]
LGTM

**Comment by opejesu2244** [comment]
Good project 😀😀😎😎

**Pull request merged**
