### PR TITLE
feat: Add Sepolia support

### PR DESCRIPTION
**Pull request by fadeev**
## Before merging

- [x] Merge https://github.com/zeta-chain/networks/pull/32
- [x] Release new version of networks (currently, using a pre-release version)
- [x] Add ZETA token consumer
- [x] Add Uniswap v2/v3 router addresses
- [x] Update networks package version in this branch

### CODE REVIEW

**Comment by fadeev** [comment]
@andresaiello I need to know `zetaTokenConsumerUniV2`, `uniswapV2Router02`, `uniswapV3Router` for Sepolia. (these addresses cannot be fetched from chain).

**Review by andresaiello — DISMISSED** [review]

**Comment by fadeev** [comment]
For Uniswap router contract address on Sepolia, I'm using the universal router from https://docs.uniswap.org/contracts/v3/reference/deployments

**Comment by fadeev** [comment]
I still don't know zeta token consumer address on Sepolia, which is needed for CCM, but I suppose we can add it later.

**Comment by fadeev** [comment]
Is this the consumer address?

https://sepolia.etherscan.io/address/0x7e792f3736751e168864106AdbAC50152641A927

**Review by lumtis — APPROVED** [review]
Addresses looks legit to me.

Wondering why do we store some addresses in duplicate in `task/addresses`?

**Comment by fadeev** [comment]
@lumtis addresses in the tasks are the ones that we cannot fetch from anywhere.

**Comment by fadeev** [comment]
Basically, these addresses are copied to the final JSON as is, the rest are fetched from chain/other contracts.

**Review by lumtis — APPROVED** [review]
Seems like the Uniswapv3 address fix is out of the scope of the PR title but LGTM

**Review by andresaiello — APPROVED** [review]

**Pull request merged**
